### PR TITLE
My branch

### PR DESCRIPTION
**Pull request by cdashbot**
it would be cool if this worked

### CODE REVIEW

**Comment by scottwittenburg** [comment]
@spackbot-test fix style

**Comment by zackgalbreath** [comment]
@spackbot-test fix style

**Comment by zackgalbreath** [comment]
@spackbot-test fix style

**Comment by scottwittenburg** [comment]
> ```shell
> ==> Running isort checks
> Fixing /tmp/tmpju_pbwfv/spack/lib/spack/spack/ci.py
> ```

Some details on how it was fixed might be nice, optionally.

**Comment by scottwittenburg** [comment]
@spackbot-test fix style

**Comment by scottwittenburg** [comment]
@spackbot-test fix style

**Comment by scottwittenburg** [comment]
@spackbot-test fix style

**Pull request closed without merging**
